default: &default
  adapter: postgresql
  host: <%= ENV['PG_HOST'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  port: <%= ENV['PG_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: funny_movie_development

test:
  <<: *default
  database: funny_movie_test

production:
  <<: *default
  database: <%= ENV['PG_DATABASE'] %>
